import type { Doc } from "./content";
import { BRAND, TOKEN_SYMBOL, TOKEN_SUPPLY_LABEL, CHAINS, STRUCTURED_BACKING_LABEL, STRUCTURED_BACKING_FULL, CRYPTOHOST_TRANSFERS, OPS_CENTER_NAME, OPS_CENTER_TAGLINE, LEGAL_JURISDICTIONS, BANKING_HUBS } from "./brand";

/** Doc pages (whitepaper, tokenomics, docs, audit, support, legal). */
export const docMap: Record<string, Doc> = {
  whitepaper: {
    eyebrow: "Whitepaper",
    title: `${TOKEN_SYMBOL} Whitepaper`,
    meta: "Versión 1.0 · 2026",
    subtitle: `Especificación técnica y económica del token ${TOKEN_SYMBOL}: respaldo en oro físico, arquitectura multi-chain y modelo híbrido Crypto · TradFi · DeFi.`,
    hasStats: true,
    stats: [
      { value: TOKEN_SUPPLY_LABEL, label: "Suministro total" },
      { value: "0,001 oz", label: "Oro por token" },
      { value: "Multi-chain", label: "BNB · ETH · MATIC" },
      { value: "No quemable", label: "Oferta fija" },
    ],
    sections: [
      { h: "Resumen ejecutivo", p: [`${TOKEN_SYMBOL} es el token nativo de ${BRAND}, un activo digital respaldado por oro físico y equivalentes financieros tangibles, desplegado sobre múltiples blockchains. Su precio de referencia se ancla al spot internacional del oro: cada unidad representa 0,001 onzas troy de oro de referencia.`, `El proyecto combina tres capas complementarias: liquidez y acceso on-chain (DeFi), estructura bancaria y legal internacional (TradFi), y reservas auditables de oro (RWA). El objetivo es ofrecer revalorización sostenible orientada a capital institucional y patrimonial, evitando esquemas especulativos.`, "Este documento describe el modelo económico, la arquitectura técnica, la estructura legal y los riesgos asociados. No constituye una oferta de inversión ni asesoramiento financiero."] },
      { h: "1. Contexto y motivación", p: ["El oro ha sido durante milenios el activo de reserva por excelencia. En la era digital, los inversores buscan exponerse a ese respaldo con la liquidez, velocidad y accesibilidad de las blockchains.", `${BRAND} responde a esa demanda con un token de suministro fijo, no minable y no quemable, verificable on-chain y respaldado por activos tangibles sujetos a viabilidad legal y regulatoria.`] },
      { h: `2. El token ${TOKEN_SYMBOL}`, p: [`${TOKEN_SYMBOL} es un token fungible desplegado en ${CHAINS.slice(0, 3).join(", ")} y otras redes. Suministro total fijo: ${TOKEN_SUPPLY_LABEL} unidades. Sin función de acuñación adicional ni de quema: la oferta permanece constante.`, "Compatibilidad con MetaMask, Trust Wallet y wallets estándar. Naturaleza: no minable, no quemable, transferible peer-to-peer."] },
      { h: "3. Anclaje al oro", p: ["El precio de referencia de CGOLD sigue al spot internacional del oro (XAU/USD). La relación nominal es 1 CGOLD = 0,001 oz troy. Un oráculo agrega fuentes de mercado para publicar el valor de referencia y mantener la correlación.", "El mercado on-chain puede operar con prima o descuento respecto al ancla, pero la señal fundamental del oro guía el arbitraje y la percepción de valor del activo."] },
      { h: "4. Modelo de valor", p: ["Respaldo estructurado en oro físico y equivalentes financieros, sujeto a auditoría periódica bajo entidad legal internacional.", "Infraestructura CRYPTOHOST con historial operativo de más de 5 millones de transferencias, garantizando liquidación automatizada y confiable.", "Estrategia de crecimiento orientada a revalorización sostenible, diseñada para inversores institucionales y patrimoniales."] },
      { h: "5. Distribución del suministro", p: ["70% adquirentes y preventa pública. 20% stake estratégico del emisor. 10% liquidez on-chain y reservas operativas.", "El suministro es fijo: no se emitirán ni destruirán tokens adicionales."] },
      { h: "6. Arquitectura multi-chain", p: [`Contratos activos y en despliegue en: ${CHAINS.join(" · ")}.`, "Red principal de lanzamiento: BNB Chain, por su base de usuarios activos, compatibilidad EVM, costes predecibles y cuota creciente en el mercado RWA.", "Migración y paridad cross-chain gestionadas mediante puentes auditados y política de liquidez coordinada."] },
      { h: "7. Infraestructura incluida", p: ["Smart contract profesional, único y verificable en exploradores de bloques.", "Integración de compra con USDT, otras criptomonedas y opciones fiat (Transak, MoonPay).", "Sistema de soporte automatizado y CRYPTOHOST. Atención humana cualificada (3 personas dedicadas durante el primer año).", "Identidad corporativa, logo oficial y brand guidelines de CryptoGold."] },
      { h: "8. Estructura legal y bancaria", p: ["Registro de entidad legal internacional (opciones: Londres, Lituania, Estonia, Hong Kong, Dubai, Suiza).", "Apertura de estructura bancaria corporativa internacional sujeta a compliance.", "Registro informativo en CoinMarketCap y estrategia de listing progresivo en exchanges fiables."] },
      { h: "9. Seguridad", p: ["Contratos auditados por firmas independientes. Código abierto y verificable on-chain.", "Self-custody: CryptoGold no custodia fondos de usuarios. La pérdida de claves privadas implica pérdida irreversible de tokens."] },
      { h: "10. Hoja de ruta", p: ["2026 Q2 — Preventa pública, despliegue BNB Chain, activación CRYPTOHOST y liquidez USDT.", "2026 Q3-Q4 — Expansión multi-chain (ETH, MATIC, SOL), registro CoinMarketCap.", "2027 — Listings progresivos en exchanges, ampliación reservas de oro y reporting institucional."] },
      { h: "11. Aviso legal", p: ["Este documento tiene carácter informativo. Invertir en criptoactivos conlleva riesgos significativos. Consulte a un asesor independiente antes de tomar decisiones de inversión.", "El respaldo en oro y activos tangibles está sujeto a viabilidad legal y regulatoria en cada jurisdicción."] },
    ],
  },
  tokenomics: {
    eyebrow: "Tokenomics",
    title: `Tokenomics de ${TOKEN_SYMBOL}`,
    meta: `Suministro fijo · ${TOKEN_SUPPLY_LABEL} ${TOKEN_SYMBOL}`,
    subtitle: "Distribución del suministro, anclaje al oro y modelo de entrega del proyecto.",
    hasStats: true,
    stats: [
      { value: TOKEN_SUPPLY_LABEL, label: "Suministro total" },
      { value: "70%", label: "Adquirentes" },
      { value: "20%", label: "Stake emisor" },
      { value: "10%", label: "Liquidez" },
    ],
    sections: [
      { h: "Distribución del suministro", p: [`Suministro total: ${TOKEN_SUPPLY_LABEL} ${TOKEN_SYMBOL}. Adquirentes y preventa: 70%. Stake estratégico del emisor: 20%. Liquidez on-chain y reservas: 10%.`, "No minable. No quemable. Oferta fija verificable en contrato."] },
      { h: "Anclaje al oro", p: ["1 CGOLD = 0,001 oz troy de oro de referencia. El precio spot del oro (XAU/USD) determina el valor de referencia del token.", "Reservas de oro físico y equivalentes financieros sujetos a auditoría periódica."] },
      { h: "Entrega del proyecto", p: ["El proyecto se entrega con respaldo estructurado en activos tangibles o equivalentes financieros, representando una reserva significativa sujeta a la estructura legal final.", "70% del suministro transferido a adquirentes. 20% retenido por el emisor como stake estratégico de alineación a largo plazo."] },
      { h: "Liquidez", p: ["El 10% destinado a liquidez garantiza operaciones de compra-venta on-chain en pools USDT/CGOLD desde el primer día.", "Sin periodos de bloqueo para compradores de preventa en la red principal."] },
    ],
  },
  docs: {
    eyebrow: "Documentación",
    title: "Documentación para desarrolladores",
    meta: "Referencia de contratos · v1",
    subtitle: `Guías de integración, direcciones de contrato y endpoints para consultar precio, oro spot, cartera y operaciones de ${TOKEN_SYMBOL}.`,
    sections: [
      { h: "Introducción", p: [`Esta documentación cubre la integración de ${TOKEN_SYMBOL} en aplicaciones: conexión de wallet, lectura de precio anclado al oro, compras con USDT y eventos on-chain.`] },
      { h: "Redes soportadas", p: [`Contratos en ${CHAINS.join(", ")}. ABI ERC-20/BEP-20 estándar. Direcciones publicadas en exploradores verificados.`] },
      { h: "Comprar e intercambiar", p: ["Compras con USDT, ETH, BTC vía pools de liquidez. Compras fiat vía Transak/MoonPay con liquidación a wallet del usuario.", "API /api/gold expone el spot del oro en USD para calcular el valor de referencia de CGOLD."] },
      { h: "Buenas prácticas", p: ["Valida direcciones de contrato contra la lista oficial. Simula operaciones antes de enviarlas. Nunca solicites claves privadas."] },
    ],
  },
  audit: {
    eyebrow: "Auditoría",
    title: "Seguridad y auditorías",
    meta: "Contratos verificados on-chain",
    subtitle: "Los contratos del protocolo han sido diseñados para auditoría independiente. Código abierto y verificable.",
    sections: [
      { h: "Alcance", p: [`Auditoría del token ${TOKEN_SYMBOL} (ERC-20/BEP-20), módulos de liquidez y puentes cross-chain.`] },
      { h: "Características del contrato", p: ["Suministro fijo en deployment. Sin función mint. Sin función burn. Transferencias estándar ERC-20."] },
      { h: "No custodia", p: [`${BRAND} no custodia fondos de usuarios. Los ${TOKEN_SYMBOL} se envían directamente a la wallet del inversor.`] },
    ],
  },
  support: {
    eyebrow: "Soporte",
    title: "Centro de soporte",
    meta: "Respuesta media < 24 h · CRYPTOHOST activo",
    subtitle: "¿Necesitas ayuda con una compra, un intercambio o tu wallet? Soporte automatizado y equipo humano dedicado.",
    sections: [
      { h: "Contacto", p: ["Escríbenos a soporte@cryptogold.io o usa el chat in-app. Equipo humano cualificado (3 personas) durante el primer año. Respuesta media inferior a 24 horas en días laborables."] },
      { h: "CRYPTOHOST", p: ["Infraestructura automatizada de transferencias con más de 5 millones de operaciones históricas. Si una operación queda pendiente, consulta el panel de estado o contacta soporte con el ID de transacción."] },
      { h: "Problemas con un pago", p: ["Compras con tarjeta se procesan en Transak o MoonPay. Compras cripto se liquidan on-chain vía CRYPTOHOST."] },
      { h: "Recuperar el acceso", p: ["CryptoGold no custodia tus claves. Recupera tu wallet con tu frase semilla. Nunca la compartas con nadie."] },
      { h: "Equipo humano (año 1)", p: ["Tres profesionales cualificados dedicados al soporte de adquirentes e integradores durante el primer año del proyecto.", "Cobertura en español e inglés. Escalado prioritario para operaciones de alto volumen e integraciones institucionales.", "Horario laboral extendido en zonas EMEA y APAC. Fuera de horario, el sistema automatizado y CRYPTOHOST mantienen la operativa."] },
      { h: "Estado del servicio", p: ["Consulta el estado de CRYPTOHOST, liquidez on-chain y proveedores de pago en /docs/status.", "Las incidencias se publican con ETA de resolución. La liquidez on-chain permite operar aunque la interfaz esté en mantenimiento."] },
    ],
  },
  "legal-structure": {
    eyebrow: "Legal y banca",
    title: "Estructura legal y bancaria",
    meta: "Entidad internacional · Compliance · 2026",
    subtitle: "Marco jurídico y financiero del proyecto CryptoGold: entidad corporativa, banca internacional y cumplimiento normativo.",
    hasStats: true,
    stats: [
      { value: "6", label: "Jurisdicciones evaluadas" },
      { value: "3", label: "Hubs bancarios" },
      { value: STRUCTURED_BACKING_LABEL, label: "Respaldo estructurado" },
      { value: "RWA", label: "Activos tangibles" },
    ],
    sections: [
      { h: "Entidad legal internacional", p: [`${BRAND} se estructura mediante registro de entidad legal en jurisdicción internacional, seleccionada según criterios de estabilidad regulatoria, tratamiento de activos tokenizados (RWA) y acceso bancario.`, `Jurisdicciones en evaluación: ${LEGAL_JURISDICTIONS.join(", ")}. La decisión final se comunicará en el white paper actualizado y en los registros corporativos públicos.`] },
      { h: "Vínculo legal con el proyecto", p: [`El token ${TOKEN_SYMBOL} está vinculado a un proyecto real con estructura legal definida: contratos verificables, política de reservas y reporting periódico.`, "El modelo combina Crypto, TradFi y DeFi bajo un mismo paraguas corporativo, sujeto a viabilidad legal y regulatoria en cada mercado."] },
      { h: "Respaldo en activos tangibles", p: [`El proyecto se entrega con respaldo estructurado estimado de hasta ${STRUCTURED_BACKING_FULL} en oro físico y equivalentes financieros tangibles.`, "Las reservas quedan sujetas a auditoría independiente. La relación nominal token-reserva se documenta en informes periódicos para inversores institucionales."] },
      { h: "Estructura bancaria", p: [`Apertura de estructura bancaria corporativa internacional en hubs como ${BANKING_HUBS.join(", ")}, sujeta a procesos KYC/AML y compliance bancario.`, "Las cuentas corporativas canalizan capital institucional hacia reservas y liquidez, complementando la operativa on-chain."] },
      { h: "Cumplimiento y reporting", p: ["Políticas AML/KYC alineadas con estándares internacionales. Due diligence para inversores institucionales y operaciones de alto volumen.", "Informes trimestrales de reservas (cuando la estructura legal esté operativa). Transparencia on-chain de suministro y contratos."] },
      { h: "Aviso", p: ["La constitución de entidad y cuentas bancarias está sujeta a aprobación regulatoria y bancaria. Este documento describe la estrategia planificada, no una garantía de resultado."] },
    ],
  },
  cryptohost: {
    eyebrow: "Infraestructura",
    title: OPS_CENTER_NAME,
    meta: `${OPS_CENTER_TAGLINE} · ${CRYPTOHOST_TRANSFERS} transferencias`,
    subtitle: "Centro de operaciones CryptoGold: transferencias, liquidación y acreditación de CGOLD a escala global.",
    hasStats: true,
    stats: [
      { value: CRYPTOHOST_TRANSFERS, label: "Transferencias históricas" },
      { value: "< 3 s", label: "Liquidación media" },
      { value: "99,9%", label: "Uptime objetivo" },
      { value: "24/7", label: "Operación automática" },
    ],
    sections: [
      { h: `Qué es ${OPS_CENTER_NAME}`, p: [`${OPS_CENTER_NAME} es el centro de operaciones que procesa transferencias cripto y fiat-to-wallet, acredita CGOLD y reconcilia operaciones sin intervención manual en el flujo estándar.`, `Con un historial operativo de más de ${CRYPTOHOST_TRANSFERS} transferencias, el sistema está diseñado para volumen institucional y retail simultáneo.`] },
      { h: "Flujos soportados", p: ["Compra con USDT, USDC, ETH, BTC → acreditación CGOLD en wallet del usuario.", `Compra con tarjeta (Transak / MoonPay) → webhook → ${OPS_CENTER_NAME} → acreditación on-chain.`, "Swaps y transferencias cross-chain coordinadas con puentes auditados."] },
      { h: "Seguridad y trazabilidad", p: ["Cada operación genera un ID único (formato CGD-XXXXXX) rastreable en historial de cartera, recibo descargable y backoffice interno.", "Reintentos automáticos ante congestión de red. Modo conservador si el oráculo de oro detecta discrepancias anómalas.", "Sin custodia centralizada: los tokens se envían siempre a la wallet del usuario."] },
      { h: "Backoffice operadores", p: ["Panel interno en /admin: dashboard, listado de transferencias, detalle por CGD-ID, reintentos manuales y regeneración del histórico visible.", "5.000 operaciones trazables en el registro público de la home, paginables vía /api/cryptohost/history.", "Acceso protegido con CRYPTOHOST_ADMIN_PASSWORD."] },
      { h: "Integración para desarrolladores", p: ["POST /api/cryptohost/transfers — registrar operación (compra, swap, fiat).", "GET /api/cryptohost/transfers?recent=N — actividad reciente pública.", "GET /api/cryptohost/status — salud del servicio e incidencias abiertas.", "Estados: pending, processing, confirmed, failed."] },
      { h: "Soporte", p: ["Si una operación queda pendiente más de 15 minutos, contacta soporte@cryptogold.io con el ID de transacción.", `Consulta /docs/status para incidencias conocidas de ${OPS_CENTER_NAME} o proveedores de pago.`] },
    ],
  },
  listings: {
    eyebrow: "Visibilidad",
    title: "CoinMarketCap y exchanges",
    meta: "Estrategia de listing progresivo · 2026–2027",
    subtitle: "Hoja de ruta para registro en CoinMarketCap, liquidez DEX y listings progresivos en exchanges fiables.",
    hasStats: true,
    stats: [
      { value: "CMC", label: "Registro previsto Q3 2026" },
      { value: "DEX", label: "Liquidez activa" },
      { value: "4 fases", label: "Plan de listing" },
      { value: TOKEN_SYMBOL, label: "Par principal USDT" },
    ],
    sections: [
      { h: "CoinMarketCap", p: [`${BRAND} prepara el registro informativo en CoinMarketCap con datos verificables de suministro, contratos multi-chain y precio anclado al oro.`, "El registro mejora la visibilidad, permite seguimiento público del token y es requisito previo para muchos exchanges centralizados."] },
      { h: "Estrategia de listing", p: ["Fase 1 — CoinMarketCap: registro informativo y datos de mercado.", "Fase 2 — DEX tier-1: profundidad de liquidez USDT/CGOLD en BNB Chain y Ethereum.", "Fase 3 — CEX regionales: exchanges regulados en EMEA y APAC.", "Fase 4 — CEX tier-1: listings progresivos en plataformas globales, sujetos a due diligence mutua."] },
      { h: "Criterios de selección de exchanges", p: ["Regulación y historial de seguridad probado.", "Soporte de pares USDT y volumen mínimo comprometido.", "Alineación con perfil institucional del proyecto — sin esquemas especulativos."] },
      { h: "Calendario orientativo", p: ["2026 Q2 — Liquidez DEX y preventa.", "2026 Q3-Q4 — Solicitud CoinMarketCap y primeros CEX regionales.", "2027 — Expansión a CEX tier-1 según volumen y cumplimiento."] },
    ],
  },
  status: {
    eyebrow: "Estado",
    title: "Estado del servicio",
    meta: "Actualizado en tiempo real · demo",
    subtitle: "Monitorización de CRYPTOHOST, liquidez on-chain, oráculo de oro y proveedores de pago.",
    hasStats: true,
    stats: [
      { value: "Operativo", label: "CRYPTOHOST" },
      { value: "Operativo", label: "Liquidez USDT/CGOLD" },
      { value: "Operativo", label: "Oráculo XAU" },
      { value: "Operativo", label: "Transak / MoonPay" },
    ],
    sections: [
      { h: "Servicios principales", p: ["CRYPTOHOST — operativo. Liquidación media < 3 s.", "Pools de liquidez BNB Chain — operativos.", "API /api/gold — operativa. Spot XAU actualizado cada 60 s.", "Compras con tarjeta — operativas vía Transak y MoonPay (demo)."] },
      { h: "Mantenimiento programado", p: ["No hay mantenimiento programado en las próximas 72 horas.", "Durante mantenimiento de interfaz, la liquidez on-chain permanece disponible para operar directamente desde wallet."] },
      { h: "Incidencias recientes", p: ["Sin incidencias abiertas en los últimos 30 días.", "Histórico de uptime CRYPTOHOST: 99,94% (últimos 12 meses)."] },
      { h: "Reportar un problema", p: ["Escríbenos a soporte@cryptogold.io con el ID de operación (CGD-XXXXXX) y captura de wallet.", "Para pagos con tarjeta, incluye también el ID del proveedor (Transak / MoonPay)."] },
    ],
  },
  terms: {
    eyebrow: "Legal",
    title: "Términos y condiciones",
    meta: "Última actualización: 2026",
    subtitle: `Condiciones de uso de la plataforma ${BRAND}. Al utilizarla, aceptas los términos descritos a continuación.`,
    sections: [
      { h: "1. Naturaleza del servicio", p: [`${BRAND} facilita la compra, intercambio y custodia self-custody del token ${TOKEN_SYMBOL}. No actuamos como entidad de custodia ni asesor de inversión.`] },
      { h: "2. Elegibilidad", p: ["Debes ser mayor de edad en tu jurisdicción y cumplir la normativa aplicable en tu país."] },
      { h: "3. Riesgos", p: [`El valor de ${TOKEN_SYMBOL} puede fluctuar. Operas bajo tu propia responsabilidad.`] },
      { h: "4. Respaldo en oro", p: ["El respaldo en oro físico y activos tangibles está sujeto a viabilidad legal y regulatoria. Consulte el whitepaper para detalles."] },
    ],
  },
  privacy: {
    eyebrow: "Legal",
    title: "Política de privacidad",
    meta: "Última actualización: 2026",
    subtitle: `Cómo tratamos tus datos cuando usas ${BRAND}.`,
    sections: [
      { h: "1. Datos que tratamos", p: ["Dirección de wallet, importes de operaciones y datos técnicos. Datos de tarjeta procesados en Transak/MoonPay; CryptoGold no los almacena."] },
      { h: "2. Finalidad", p: ["Ejecutar operaciones, mostrar cartera y prevenir fraude. No vendemos tus datos."] },
      { h: "3. Tus derechos", p: ["Solicita acceso o supresión en privacidad@cryptogold.io."] },
    ],
  },
  risks: {
    eyebrow: "Legal",
    title: "Advertencia de riesgos",
    meta: "Lee esto antes de invertir",
    subtitle: "Invertir en criptoactivos conlleva riesgos significativos.",
    sections: [
      { h: "Volatilidad", p: [`Aun anclado al oro, ${TOKEN_SYMBOL} puede operar con prima o descuento en mercados on-chain.`] },
      { h: "Riesgo regulatorio", p: ["La regulación de activos respaldados por oro varía por jurisdicción."] },
      { h: "Riesgo tecnológico", p: ["Contratos inteligentes pueden contener vulnerabilidades. Protege tus claves privadas."] },
      { h: "Sin asesoramiento", p: ["Esta plataforma no ofrece asesoramiento financiero. Consulta a un profesional independiente."] },
    ],
  },
};

export const docSlugs = Object.keys(docMap);
